### ISSUE TITLE
Failed prop type

### ISSUE THREAD

**Issue by VincentLeung** [wadehrarshpreet/react-svg-draw#1]
I got these kind of error when running the sample:

Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `Defs`, expected `object`.
Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `G`, expected `object`.
Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `SVG`, expected `object`.

Any suggested way to get rid of them?  Thanks.

**Comment by wadehrarshpreet** [comment]
Fixed in v0.0.12
